window.FIVITA_SHOP = {
  categories: [
    {
      id: "body-care",
      name: "身体护理系统",
      summary: "植萃能量、修复肌肤、促进循环，唤活身心。",
      image: "/assets/shop/category-body-care.jpg",
      subcategories: ["洗护清洁", "身体保养", "局部护理", "工具/护理配件"],
    },
    {
      id: "food",
      name: "营养结构管理",
      summary: "科学营养搭配、平衡结构，由内而外焕发活力。",
      image: "/assets/shop/category-food.jpg",
      subcategories: [
        "冲泡粉剂/代用茶",
        "主食代餐",
        "健康零食",
        "干果蜜饯",
        "草本茶饮",
        "花果醋",
        "慢熬膏方",
        "儿童零食",
      ],
    },
    {
      id: "home",
      name: "空间健康系统",
      summary: "香氛、清洁与居家仪式，为日常空间建立舒适秩序。",
      image: "/assets/shop/category-home.jpg",
      subcategories: ["睡眠香氛", "空间净化", "居家清洁", "工具/补充装"],
    },
    {
      id: "travel",
      name: "随身健康系统",
      summary: "轻量、便携、即时补给，陪伴通勤与旅途。",
      image: "/assets/shop/category-travel.jpg",
      subcategories: ["口腔护理", "精油/滚珠香氛", "营养补给", "便携套组"],
    },
  ],
  products: [
    product("herbal-body-wash", "草本沐浴露", "body-care", "洗护清洁", "/assets/category-body-care.jpg"),
    product("body-lotion", "植萃身体乳", "body-care", "身体保养", "/assets/category-body-care.jpg"),
    product("scalp-tonic", "头皮调理精华", "body-care", "局部护理", "/assets/category-aromatherapy.jpg"),
    product("herbal-patch", "草本舒缓贴", "body-care", "局部护理", "/assets/gift-fire.jpg"),
    product("massage-oil", "草本按摩油", "body-care", "工具/护理配件", "/assets/category-aromatherapy.jpg"),
    product("sleep-mist", "睡眠香氛喷雾", "home", "睡眠香氛", "/assets/category-ritual-living.jpg"),
    product("reed-diffuser", "草本藤条香氛", "home", "空间净化", "/assets/shop/category-home.jpg"),
    product("room-spray", "空间净化喷雾", "home", "空间净化", "/assets/category-aromatherapy.jpg"),
    product("warm-compress-tool", "温敷护理工具", "home", "居家清洁", "/assets/gift-wood.jpg"),
    product("foot-bath-sachet", "草本足浴包", "home", "工具/补充装", "/assets/category-ritual-living.jpg"),
    product("oral-spray", "草本口腔喷雾", "travel", "口腔护理", "/assets/shop/category-travel.jpg"),
    product("pulse-roll-on", "脉点滚珠香氛", "travel", "精油/滚珠香氛", "/assets/shop/category-travel.jpg"),
    product("immune-tablets", "日常营养片", "travel", "营养补给", "/assets/gift-metal.jpg"),
    product("energy-boost-sachet", "随身能量包", "travel", "便携套组", "/assets/shop/category-travel.jpg"),
    product("fp0001", "五红红曲醪糟粉", "food", "冲泡粉剂/代用茶", "/assets/products/fp0001-wuhong-hongqu-laozao-powder.jpg", "红曲米、红豆、红枣、红皮花生、枸杞、醪糟粉"),
    product("fp0002", "七白粉", "food", "冲泡粉剂/代用茶", "/assets/products/fp0002-qibai-powder.jpg", "银耳、山药、莲子、薏苡仁、茯苓、百合、杏仁"),
    product("fp0003", "五黑粉", "food", "冲泡粉剂/代用茶", "/assets/products/fp0003-wuhei-powder.jpg", "黑芝麻、黑豆、黑米、黑枸杞、桑葚"),
    product("fp0004", "八珍粉", "food", "冲泡粉剂/代用茶", "/assets/products/fp0004-bazhen-powder.jpg", "山药、芡实、莲子、茯苓、薏苡仁、红枣、百合、燕麦"),
    product("fp0005", "米糠粉", "food", "冲泡粉剂/代用茶", "/assets/products/fp0005-mikang-powder.jpg", "米糠、燕麦粉、糙米粉"),
    product("fp0006", "人参五宝茶", "food", "冲泡粉剂/代用茶", "/assets/products/fp0006-renshen-wubao-tea.jpg", "人参、大麦、枸杞、大枣、覆盆子、桑葚、玛咖粉"),
    product("fp0007", "冷杉清甘茶", "food", "冲泡粉剂/代用茶", "/assets/products/fp0007-lengshan-qinggan-tea.jpg", "冷杉叶、桑椹、枇杷叶、甘蔗、雪梨干、陈皮、白果、甘草、薄荷"),
    product("fp0008", "无花果种子循环茶", "food", "冲泡粉剂/代用茶", "/assets/products/fp0008-seed-cycle-tea.jpg", "亚麻籽、南瓜籽、芝麻、葡萄籽、黑豆、黑枸杞、桑葚、无花果"),
    product("fp0009", "白小米", "food", "主食代餐", "/assets/products/fp0009-bai-xiaomi.jpg", "白小米"),
    product("fp0010", "四色小米", "food", "主食代餐", "/assets/products/fp0010-sise-xiaomi.jpg", "黄小米、黑小米、红小米、绿小米"),
    product("fp0011", "山药薏米线面", "food", "主食代餐", "/assets/products/fp0011-shanyao-yimi-mian.jpg", "小麦粉、山药粉、薏苡仁粉"),
    product("fp0012", "谷物代餐奶昔", "food", "主食代餐", "/assets/products/fp0012-gRAIN-meal-shake.jpg", "燕麦粉、黄芪、麦芽、红枣、茯苓、莲子、佛手、栀子、玫瑰花"),
    product("fp0013", "液体沙拉", "food", "主食代餐", "/assets/products/fp0013-liquid-salad.jpg", "青提汁、番石榴汁、膳食纤维、果蔬浓缩液"),
    product("fp0014", "冻干虫草花鸡煌粥", "food", "主食代餐", "/assets/products/fp0014-chongcao-jihuang-zhou.jpg", "大米、鸡肉、虫草花、香菇、胡萝卜"),
    product("fp0015", "红参丸", "food", "健康零食", "/assets/products/fp0015-hongshen-wan.jpg", "红参、蜂蜜"),
    product("fp0016", "山楂丸", "food", "健康零食", "/assets/products/fp0016-shanzha-wan.jpg", "山楂、麦芽、蜂蜜"),
    product("fp0017", "核桃桑葚黑芝麻丸", "food", "健康零食", "/assets/products/fp0017-heizhima-wan.jpg", "核桃仁、桑葚、黑芝麻、黑豆、蜂蜜"),
    product("fp0018", "薏仁脆", "food", "健康零食", "/assets/products/fp0018-yiren-cui.jpg", "薏苡仁、糙米、燕麦"),
    product("fp0019", "复硒红颜饼干", "food", "健康零食", "/assets/products/fp0019-fuxi-hongyan-binggan.jpg", "小麦粉、红甜菜粉、胶原蛋白肽、硒酵母"),
    product("fp0020", "番茄坚果种籽脆", "food", "健康零食", "/assets/products/fp0020-fanqie-jianguo-zhongzi-cui.jpg", "番茄粉、巴旦木、南瓜籽、葡萄籽、芝麻"),
    product("fp0021", "柚子胡椒坚果种籽脆", "food", "健康零食", "/assets/products/fp0021-youzi-hujiao-jianguo-zhongzi-cui.jpg", "柚子、胡椒、腰果、南瓜籽、葡萄籽"),
    product("fp0022", "五指毛桃茯苓益湿糕", "food", "健康零食", "/assets/products/fp0022-wuzhi-maotao-fuling-yishi-gao.jpg", "五指毛桃、茯苓、薏苡仁、山药、红豆"),
    product("fp0023", "茯苓鸡内金焦饼", "food", "健康零食", "/assets/products/fp0023-fuling-jineijin-jiao-bing.jpg", "茯苓、鸡内金、山药、麦芽"),
    product("fp0024", "山西炒琪", "food", "健康零食", "/assets/products/fp0024-shanxi-chaoqi.jpg", "小麦、燕麦、黑芝麻"),
    product("fp0025", "陈皮紫苏乌梅片", "food", "干果蜜饯", "/assets/shop/category-food.jpg", "陈皮、紫苏、乌梅"),
    product("fp0026", "酒制黄精", "food", "干果蜜饯", "/assets/shop/category-food.jpg", "黄精"),
    product("fp0027", "山药干", "food", "干果蜜饯", "/assets/shop/category-food.jpg", "山药"),
    product("fp0028", "一整根人参水", "food", "草本茶饮", "/assets/shop/category-food.jpg", "人参、水"),
    product("fp0029", "酸角西梅菊苣饮", "food", "草本茶饮", "/assets/shop/category-food.jpg", "酸角、西梅、菊苣"),
    product("fp0030", "苹果黄芪水", "food", "草本茶饮", "/assets/shop/category-food.jpg", "苹果、黄芪"),
    product("fp0031", "大马士革玫瑰康普茶", "food", "草本茶饮", "/assets/shop/category-food.jpg", "康普茶、大马士革玫瑰"),
    product("fp0032", "黄芪饮", "food", "草本茶饮", "/assets/shop/category-food.jpg", "黄芪"),
    product("fp0033", "肉桂苹果醋", "food", "花果醋", "/assets/shop/category-food.jpg", "苹果醋、肉桂"),
    product("fp0034", "覆盆子柠檬草醋", "food", "花果醋", "/assets/shop/category-food.jpg", "覆盆子醋、柠檬草"),
    product("fp0035", "石榴玫瑰醋", "food", "花果醋", "/assets/shop/category-food.jpg", "石榴醋、玫瑰"),
    product("fp0036", "阿胶人参蜜", "food", "慢熬膏方", "/assets/shop/category-food.jpg", "蜂蜜、阿胶、人参"),
    product("fp0037", "玉灵膏", "food", "慢熬膏方", "/assets/shop/category-food.jpg", "龙眼肉、西洋参、蜂蜜"),
    product("fp0038", "酸枣仁膏", "food", "慢熬膏方", "/assets/shop/category-food.jpg", "酸枣仁、茯苓、百合、蜂蜜"),
    product("fp0039", "怀姜枣膏", "food", "慢熬膏方", "/assets/shop/category-food.jpg", "怀姜、红枣、红糖"),
    product("fp0040", "黄芪红参保元膏", "food", "慢熬膏方", "/assets/shop/category-food.jpg", "黄芪、红参、枸杞、蜂蜜"),
    product("fp0041", "五黑小雪饼", "food", "儿童零食", "/assets/shop/category-food.jpg", "黑芝麻、黑豆、黑米、糯米"),
    product("fp0042", "八珍格仔饼", "food", "儿童零食", "/assets/shop/category-food.jpg", "小麦粉、山药、莲子、茯苓、薏苡仁、芡实、红枣、百合"),
  ],
};

function product(id, name, category, subcategory, image, ingredients = "") {
  return {
    id,
    name,
    category,
    subcategory,
    description: `${name}，属于${subcategory}系列，适合作为日常健康生活的轻量补充。`,
    image,
    tags: ["草本配方", "自然食养", "日常仪式"],
    ingredients,
  };
}
